Jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USERNAME}
          password: ${JENKINS_ADMIN_PASSWORD}
        - id: ${JENKINS_AGENT_USERNAME}
          password: ${JENKINS_AGENT_PASSWORD}
    authorizationStrategy:
    roleBased:
      roles:
        global:
          - id: "admin"
            name: Administer
            permissions:
              - Overall/Administer
            entries:
              - user: ${JENKINS_ADMIN_USERNAME}
          - id: "userTest"
            name: Agent
            permissions:
              - Overall/Read
              - Agent/Connect
              - Agent/Disconnect
              - Agent/Build
            entries:
              - user: ${JENKINS_AGENT_USERNAME}
    tool:
      git:
        installations:
          - name: git
            home: /usr/local/bin/git
    jobs:
    - file: /var/jenkins_home/casc_configs/Job_dsl.groovy